"""card images + app_settings

Revision ID: 93821a47fac1
Revises: dfdd97720cc8
Create Date: 2026-05-19 11:52:09.232666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93821a47fac1'
down_revision = 'dfdd97720cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('special_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special_cards', schema=None) as batch_op:
        batch_op.drop_column('card_image_url')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('card_image_url')

    op.drop_table('app_settings')
    # ### end Alembic commands ###
