"""initial schema (8 tables)

Revision ID: dfdd97720cc8
Revises: 
Create Date: 2026-05-16 14:37:52.948866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdd97720cc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_key', sa.String(length=20), nullable=False),
    sa.Column('suit', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.String(length=5), nullable=False),
    sa.Column('alumni_name', sa.String(length=50), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('business_desc', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('wechat', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('company_address', sa.String(length=200), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('team_size', sa.String(length=20), nullable=True),
    sa.Column('latest_news', sa.Text(), nullable=True),
    sa.Column('alumni_quote', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index('idx_suit_rank', ['suit', 'rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_card_key'), ['card_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_cards_industry'), ['industry'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('config_path', sa.String(length=200), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_game_id'), ['game_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_is_enabled'), ['is_enabled'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('attempt_type', sa.String(length=20), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_phone_attempted', ['phone', 'attempted_at'], unique=False)

    op.create_table('sms_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.create_index('idx_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_phone_purpose', ['phone', 'purpose'], unique=False)

    op.create_table('special_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('motto', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('jwt_token', sa.Text(), nullable=True),
    sa.Column('jwt_expires_at', sa.DateTime(), nullable=True),
    sa.Column('jwt_refresh_token', sa.Text(), nullable=True),
    sa.Column('jwt_refresh_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('daily_game_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_game_counts', schema=None) as batch_op:
        batch_op.create_index('idx_user_game_date', ['user_id', 'game_id', 'game_date'], unique=True)

    op.create_table('game_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_key', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('cards_used', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_scores', schema=None) as batch_op:
        batch_op.create_index('idx_played_at', ['played_at'], unique=False)
        batch_op.create_index('idx_user_game', ['user_id', 'game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_scores', schema=None) as batch_op:
        batch_op.drop_index('idx_user_game')
        batch_op.drop_index('idx_played_at')

    op.drop_table('game_scores')
    with op.batch_alter_table('daily_game_counts', schema=None) as batch_op:
        batch_op.drop_index('idx_user_game_date')

    op.drop_table('daily_game_counts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    op.drop_table('special_cards')
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_phone_purpose')
        batch_op.drop_index('idx_expires_at')

    op.drop_table('sms_codes')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_phone_attempted')

    op.drop_table('login_attempts')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_games_game_id'))

    op.drop_table('games')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_industry'))
        batch_op.drop_index(batch_op.f('ix_cards_card_key'))
        batch_op.drop_index('idx_suit_rank')

    op.drop_table('cards')
    # ### end Alembic commands ###
